builds:
  - env:
      - CGO_ENABLED=0
    binary:
      rospo
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - replacements:
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

    name_template: "rospo_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
